"""
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        str = s + t
        ch = 0
        print(str)
        for i in str:
            ch = ch^ord(i)
            print(ch)
        return chr(ch)

s_1 = "abcd"
t_1 = "abcde"

s = Solution()
print(s.findTheDifference(s=s_1, t=t_1))

