"""
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        char_dic = {}
        if len(s) > len(t):
            for char in t:
                if char in char_dic:
                    char_dic[char] += 1
                else:
                    char_dic[char] = 1
            print(char_dic)
            for char in s:
                if char in char_dic:
                    if char_dic[char] == 0:
                        return char
                    char_dic[char] -= 1
                else:
                    return char
        else:
            for char in s:
                if char in char_dic:
                    char_dic[char] += 1
                else:
                    char_dic[char] = 1
            print(char_dic)
            for char in t:
                if char in char_dic:
                    if char_dic[char] == 0:
                        return char
                    char_dic[char] -= 1
                else:
                    return char
        

s_1 = "abcd"
t_1 = "abcde"

s = Solution()
print(s.findTheDifference(s=s_1, t=t_1))

